config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
  resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, inclusion: { in: CATEGORY}

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, :inclusion => { :in => 0..5 }, :presence => { :message => " must be within 0-5" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update]
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def show
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

   private

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :category)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

 def destroy
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

   private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <div >
  <p>  <%= simple_form_for(@restaurant) do |f| %> </p>
   <p> <%= f.input :name %> </p>
    <p>  <%= f.input :address %> </p>
    <p>  <%= f.input :phone_number %> </p>
   <p>  <%= f.input :category, collection: Restaurant::CATEGORY %> </p>
    <%= f.submit "Add New Restaurant", class:'btn btn-info text-white w-100' %>
  <% end %>
  </div>
</div>

app/views/restaurants/edit.html.erb
<h1 class="text-center mt-5"> Editing Restaurant</h1>
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="d-flex  ml-5">
    <div style="width:300px;height:200px;" class="border mt-5 p-3 ">
      <h2><%= restaurant.name %></h2>
      <p><%= restaurant.address %></p>
      <p><%= restaurant.category %></p>
      <%= link_to "See more", restaurant %>
    </div>
  <div>
<% end %>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<div class="container">
  <h1 class="text-center mt-5"> <%= @restaurant.name %> </h1>
  <p class="text-center"> Address: <%= @restaurant.address %> </p>
  <p class="text-center"> Phone Number: <%= @restaurant.phone_number %> </p>

  <p class="text-center">All the reviews</p>

  <% @restaurant.reviews.each do |review| %>
  <p class="text-center border p-5 mb-3 "><%= review.content %> <br> ★★★ <%= review.rating %></p>

</div>

  <p class="text-center"> <%= link_to "Delete review", review_path(review), method: :delete, data: {confirm: "Are you sure?"}  %> </p>
  <% end %>
  <p class="text-center"> <%= link_to "Reviews", new_restaurant_review_path(@restaurant) %> </p>
  <p class="text-center" > <%= link_to "All Restaurants", restaurants_path %> |
   <%= link_to "Edit", edit_restaurant_path(@restaurant) %> </p>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Write a review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit  class:'btn btn-primary text-white w-100'%>
  <% end %>
</div>